# Generated by Django 5.2 on 2025-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, help_text='Image représentative de la catégorie', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='image',
            field=models.ImageField(blank=True, help_text='Image représentative de la sous-catégorie', null=True, upload_to='sous_categories/'),
        ),
    ]
