# Generated by Django 5.2 on 2025-05-26 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorie_image_souscategorie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='ShopExcellence', help_text='Nom de votre boutique', max_length=100)),
                ('slogan', models.CharField(default='Votre boutique de confiance', help_text='Slogan de votre boutique', max_length=200)),
                ('description', models.TextField(default='Une expérience shopping moderne et intuitive', help_text='Description de votre boutique')),
                ('email', models.EmailField(blank=True, help_text='Email de contact principal', max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone principal', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('telephone_2', models.CharField(blank=True, help_text='Numéro de téléphone secondaire', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp (avec indicatif pays)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('adresse', models.TextField(blank=True, help_text='Adresse physique complète', null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pays', models.CharField(blank=True, default='France', max_length=100, null=True)),
                ('lien_google_maps', models.URLField(blank=True, help_text='Lien vers votre localisation Google Maps', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Lien vers votre page Facebook', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Lien vers votre compte Instagram', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Lien vers votre compte Twitter', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Lien vers votre page LinkedIn', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Lien vers votre chaîne YouTube', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='Lien vers votre compte TikTok', null=True)),
                ('horaires_lundi', models.CharField(blank=True, help_text='Ex: 9h00 - 18h00 ou Fermé', max_length=100, null=True)),
                ('horaires_mardi', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires_mercredi', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires_jeudi', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires_vendredi', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires_samedi', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires_dimanche', models.CharField(blank=True, max_length=100, null=True)),
                ('a_propos', models.TextField(blank=True, help_text='Texte de présentation de votre entreprise', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo de votre boutique', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Icône du site (favicon)', null=True, upload_to='site/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
