# Generated by Django 5.2 on 2025-05-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_siteconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
    ]
